#' Predict method for objects of class mff
#'
#' @description
#' The \emph{predict} method for objects of class \emph{mff} is used to generate predictions from the Meta
#' Fuzzy Function framework on the test dataset.
#'
#' @param object an object of class mff (returned by mff() or tune.mff()).
#' @param pred_matrix numeric matrix (\eqn{N_{test} \times M}) of base predictions for the new data (e.g.,
#' test set).
#' @param type 'best' uses the optimal configuration/cluster selected by tune.mff(); 'all' returns outputs
#' for all tuned configurations.
#' @param ... further arguments passed to or from other methods.
#'
#' @details
#' In this setting, the input to \emph{predict} is the matrix of test-set predictions produced by the base
#' models that were trained in the earlier stage using \emph{model.train}.
#'
#' Let \eqn{X_{test} \in \mathbb{R}^{N_{test} \times M}}{X_test \in R^{N_{test} \times M}} denote the prediction matrix of \eqn{M} trained base models on the test dataset,
#' where \eqn{N_{test}} is the number of test observations. Each column of \eqn{X_{test}} corresponds to the predictions
#' generated by a single base learner. Using the membership-based weight matrix \eqn{W = [w_{mc}]} obtained
#' during validation, meta fuzzy function predictions on the test set are computed as
#'
#' \deqn{\hat{y}_{MFF,test}^{(c)} = \sum_{m=1}^{M} w^{(m)(c)} \hat{y}_{test}^{(m)} \quad (11)}{y_hat_{MFF,test}^{(c)} = sum_{m=1}^{M} w^{(m)(c)} y_hat_{test}^{(m)} (11)}
#'
#' where \eqn{\hat{y}_{test}^{(m)}} denotes the test-set prediction vector produced by base model \eqn{m}, and \eqn{c = 1, \dots, C} indexes
#' the meta fuzzy functions.
#'
#' The predict function supports two prediction modes, controlled by the type argument:
#' \itemize{
#'   \item type = "best" returns predictions obtained from the single meta fuzzy function that achieved
#'   the optimal validation performance during training or tuning (see Eq. 9).
#'   \item type = "all" returns predictions from all meta fuzzy functions, allowing users to examine
#'   alternative predictive components within the MFF model.
#' }
#'
#' When type = "best" is selected, the final prediction for test observation \eqn{i} is given by
#'
#' \deqn{\hat{y}_{i,final} = \sum_{m=1}^{M} w^{(m)(c^*)} \hat{y}_{i,test}^{(m)} \quad (12)}{\hat{y}_{i,final} = \sum_{m=1}^{M} w^{(m)(c^*)} \hat{y}_{i,test}^{(m)} (12)}
#'
#' where \eqn{c^*} denotes the index of the best-performing meta fuzzy function selected based on validation
#' performance.
#'
#' Computes cluster-wise predictions via membership-weighted aggregation of base-model
#' predictions. For inspection and reporting purposes, a rounded copy of the membership
#' weights (four decimal places) is returned.
#'
#' If a single best-performing cluster is defined via tune.mff, the corresponding weight vector is
#' also returned.
#'
#' @return
#' \itemize{
#'   \item \code{mff_preds}: A numeric matrix of meta fuzzy function predictions on the test set. When
#'   "best", this matrix reduces to a single column.
#'  \item \code{mff_weights}: The membership based weight matrix. If a single meta fuzzy function is
#'  selected, the corresponding weight vector is returned.
#' }
#'
#'
#' @seealso \code{\link{mff}}, \code{\link{tune.mff}}, \code{\link{evaluate}}
#'
#' @examples
#' set.seed(123)
#' y_valid <- seq_len(30) + stats::rnorm(30, sd = 0.2)
#' pred_valid <- cbind(
#'   model_a = y_valid + stats::rnorm(30, sd = 0.3),
#'   model_b = y_valid + stats::rnorm(30, sd = 0.4),
#'   model_c = y_valid + stats::rnorm(30, sd = 1.2),
#'   model_d = y_valid + stats::rnorm(30, sd = 1.4)
#' )
#' fit <- tune.mff(
#'   pred_valid, y_valid,
#'   max_c = 3, mff.method = "kmeans",
#'   nstart = 10, parallel = FALSE, logging = FALSE
#' )
#' out <- predict(fit, pred_matrix = pred_valid, type = "best")
#' head(out$mff_preds)
#' out$mff_weights
#'
#' @export
predict.mff <- function(object, pred_matrix, type = c("best", "all"), ...) {

  if (!inherits(object, "mff") || is.null(object$weights) ||
      !is.matrix(object$weights)) {
    stop("'object' must be a valid fitted MFF object.", call. = FALSE)
  }
  .validate_new_prediction_matrix(pred_matrix, object$weights)
  type <- match.arg(type)

  if (type == "best") {

    if (is.null(object$best_weight)) {
      stop(paste0(
        "type = 'best' requires an MFF object tuned on validation data. ",
        "Use tune.mff() or set type = 'all'."
      ), call. = FALSE)
    }
    weights <- object$best_weight

  } else {
    weights <- object$weights
  }

  preds <- pred_matrix %*% weights

  list(
    mff_preds   = preds,
    mff_weights = round(weights, 4)
  )
}

